# Generated by Django 6.1 on 2026-09-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('pseudonimo', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('fecha_defuncion', models.DateField(null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.pais')),
            ],
        ),
    ]
