# Generated by Django 6.1 on 2026-09-25 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_pais_habilitado_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('comuna', models.CharField(max_length=60, verbose_name='Comuna')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Comunas de Chile, data de SUBDERE. Pertenece a una provincia específica.',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data de estado físico de ejemplares en la biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=30, verbose_name='Género Literario')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Géneros literarios asociados a subgéneros.',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=30, verbose_name='Idioma')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data de idiomas para asociar a publicaciones.',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Provincias de Chile, data de SUBDERE. Pertenece a una región específica.',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('region', models.CharField(max_length=30, verbose_name='Región')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Regiones de Chile, data de SUBDERE.',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Data de ubicación física de ejemplares en la biblioteca.',
            },
        ),
        migrations.AlterModelTableComment(
            name='autor',
            table_comment='Datos de autores asociados a publicaciones/libros.',
        ),
        migrations.AlterModelTableComment(
            name='pais',
            table_comment='Información de paises del mundo, para asociar a autores y lectores.',
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='pais',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_defuncion',
            field=models.DateField(null=True, verbose_name='Fecha Defunción'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencias.pais'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(max_length=50, null=True, verbose_name='Pseudónimo'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso_2',
            field=models.CharField(max_length=2, verbose_name='ISO 2'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso_3',
            field=models.CharField(max_length=3, verbose_name='ISO 3'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(max_length=30, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100, null=True, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, null=True, verbose_name='Número')),
                ('departamento', models.CharField(max_length=10, null=True, verbose_name='Dpto/Oficina')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.comuna')),
            ],
            options={
                'db_table_comment': 'Provincias de Chile, data de SUBDERE. Pertenece a una región específica.',
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('web', models.URLField(null=True, verbose_name='WWW')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencias.direccion')),
            ],
            options={
                'db_table_comment': 'Datos de biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('web', models.URLField(null=True, verbose_name='WWW')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencias.direccion')),
            ],
            options={
                'db_table_comment': 'Datos de empresas encargadas de publicaciones.',
            },
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateField(verbose_name='Fecha Edición')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.editorial')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.idioma')),
            ],
            options={
                'db_table_comment': 'Data específica de una publicación realizada por una editorial.',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('paginas', models.IntegerField(verbose_name='Cantidad Páginas')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.autor')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.biblioteca')),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.edicion')),
            ],
            options={
                'db_table_comment': 'Data específica de libros publicados pertenecientes a la bilbioteca.',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=50, verbose_name='Código Barras')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.estado')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.libro')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.ubicacion')),
            ],
            options={
                'db_table_comment': 'Copias de un libro disponibles para préstamos en biblioteca.',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.region'),
        ),
        migrations.CreateModel(
            name='SubGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenero', models.CharField(max_length=30, verbose_name='Sub-Género Literario')),
                ('descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.genero')),
            ],
            options={
                'db_table_comment': 'Subgéneros literarios asociados a publicaciones/libros.',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='subgenero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.subgenero'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('contrasenia', models.CharField(max_length=128, null=True)),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.biblioteca')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencias.direccion')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencias.pais')),
            ],
            options={
                'db_table_comment': 'Registro de usuarios de biblioteca.',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Préstamo')),
                ('fecha_devolucion', models.DateTimeField(verbose_name='Fecha Devolución')),
                ('fecha_retorno', models.DateTimeField(null=True, verbose_name='Fecha Retorno')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.inventario')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.usuario')),
            ],
            options={
                'db_table_comment': 'Registro de préstamo de libros en la biblioteca.',
            },
        ),
    ]
